<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x64</PlatformTarget>
    <ApplicationIcon />
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>viewer</AssemblyTitle>
    <AssemblyProduct>viewer</AssemblyProduct>
    <AssemblyDescription>Integrated Pak and L1 map viewer</AssemblyDescription>
  </PropertyGroup>
</Project>
